spring:
  application:
    name: application
  profiles:
    active: local
  config:
    import:
      - datastore-h2.yml
      - datastore-redis.yml
      - external.yml

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: alpha

---
spring:
  config:
    activate:
      on-profile: beta

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: release